# Generated by Django 4.2.1 on 2023-05-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articulo_autor_alter_perfil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='autor',
        ),
    ]
