# Generated by Django 4.2.1 on 2023-05-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_articulo_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
