# Generated by Django 4.2.1 on 2023-05-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_remove_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='link_pagina',
            field=models.URLField(blank=True),
        ),
    ]
