# Generated by Django 4.2.1 on 2023-05-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_perfil_descripcion_perfil_link_pagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='link_pagina',
        ),
    ]
